export const Theme = {
  "base": "vs-dark",
  "inherit": true,
  "rules": [
    { "token": "", "foreground": "D4D4D4", "background": "181A1F" },
    { "token": "invalid", "foreground": "F14C4C" },
    { "token": "emphasis", "fontStyle": "italic" },
    { "token": "strong", "fontStyle": "bold" },
    { "token": "variable", "foreground": "DED47E" },
    { "token": "variable.predefined", "foreground": "DED47E" },
    { "token": "variable.parameter", "foreground": "DED47E" },
    { "token": "constant", "foreground": "80BBFF" },
    { "token": "comment", "foreground": "737780" },
    { "token": "number", "foreground": "F48CCA" },
    { "token": "number.hex", "foreground": "F48CCA" },
    { "token": "regexp", "foreground": "81D99F" },
    { "token": "annotation", "foreground": "81CFE0" },
    { "token": "type", "foreground": "81CFE0" },
    { "token": "delimiter", "foreground": "D4D4D4" },
    { "token": "key", "foreground": "D4D4D4" },
    { "token": "string", "foreground": "81D99F" },
    { "token": "string.sql", "foreground": "B38DFF" },
    { "token": "keyword", "foreground": "B38DFF" },
    { "token": "keyword.control", "foreground": "B38DFF" },
    { "token": "keyword.declare", "foreground": "B38DFF" },
    { "token": "keyword.if", "foreground": "B38DFF" },
    { "token": "keyword.then", "foreground": "B38DFF" },
    { "token": "keyword.for", "foreground": "B38DFF" },
    { "token": "keyword.return", "foreground": "B38DFF" },
    { "token": "function", "foreground": "F29D79" },
    { "token": "function.call", "foreground": "F29D79" },
    { "token": "boolean", "foreground": "80BBFF" },
    { "token": "delimiter.parenthesis.1", "foreground": "FFD602" },
    { "token": "delimiter.parenthesis.2", "foreground": "DA70D6" },
    { "token": "delimiter.parenthesis.3", "foreground": "169FFF" },
    { "token": "delimiter.bracket.1", "foreground": "FFD602" },
    { "token": "delimiter.bracket.2", "foreground": "DA70D6" },
    { "token": "delimiter.bracket.3", "foreground": "169FFF" },
    { "token": "delimiter.curly.1", "foreground": "FFD602" },
    { "token": "delimiter.curly.2", "foreground": "DA70D6" },
    { "token": "delimiter.curly.3", "foreground": "169FFF" },
  ],
  "colors": {
    "editor.foreground": "#D4D4D4",
    "editor.background": "#181A1F",
    "editor.selectionBackground": "#212127",
    "editor.lineHighlightBackground": "#1a1a1f",
    "editorCursor.foreground": "#c084fc",
    "editorWhitespace.foreground": "#3B3A32",
    "editorIndentGuide.activeBackground": "#c084fc",
    "editor.selectionHighlightBorder": "#1d1d20",
    "editorGutter.background": "#181A1F"
  }
};